[[constraint]]
  name = "cloud.google.com/go"
  version = ">=0.46.0"

[[constraint]]
  branch = "master"
  name = "github.com/gedex/inflector"

[[constraint]]
  branch = "master"
  name = "github.com/knq/snaker"

[[constraint]]
  name = "google.golang.org/api"
  version = ">=0.10.0"

[prune]
  go-tests = true
  unused-packages = true
